<?php

namespace ContainerJcyxi3i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ao61eDYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ao61eDY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ao61eDY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\TaskController::creation' => ['privates', '.service_locator.rTFNwxm', 'get_ServiceLocator_RTFNwxmService', true],
            'App\\Controller\\TaskController::delete' => ['privates', '.service_locator.1Kj2Gyu', 'get_ServiceLocator_1Kj2GyuService', true],
            'App\\Controller\\TaskController::detail' => ['privates', '.service_locator.ATFD0HV', 'get_ServiceLocator_ATFD0HVService', true],
            'App\\Controller\\TaskController::edit' => ['privates', '.service_locator.X4aaTot', 'get_ServiceLocator_X4aaTotService', true],
            'App\\Controller\\TaskController::index' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\TaskController::myTasks' => ['privates', '.service_locator.st3ASTR', 'get_ServiceLocator_St3ASTRService', true],
            'App\\Controller\\UserController::login' => ['privates', '.service_locator._c4TEJN', 'get_ServiceLocator_C4TEJNService', true],
            'App\\Controller\\UserController::register' => ['privates', '.service_locator..d.FzjH', 'get_ServiceLocator__D_FzjHService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\TaskController:creation' => ['privates', '.service_locator.rTFNwxm', 'get_ServiceLocator_RTFNwxmService', true],
            'App\\Controller\\TaskController:delete' => ['privates', '.service_locator.1Kj2Gyu', 'get_ServiceLocator_1Kj2GyuService', true],
            'App\\Controller\\TaskController:detail' => ['privates', '.service_locator.ATFD0HV', 'get_ServiceLocator_ATFD0HVService', true],
            'App\\Controller\\TaskController:edit' => ['privates', '.service_locator.X4aaTot', 'get_ServiceLocator_X4aaTotService', true],
            'App\\Controller\\TaskController:index' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\TaskController:myTasks' => ['privates', '.service_locator.st3ASTR', 'get_ServiceLocator_St3ASTRService', true],
            'App\\Controller\\UserController:login' => ['privates', '.service_locator._c4TEJN', 'get_ServiceLocator_C4TEJNService', true],
            'App\\Controller\\UserController:register' => ['privates', '.service_locator..d.FzjH', 'get_ServiceLocator__D_FzjHService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\TaskController::creation' => '?',
            'App\\Controller\\TaskController::delete' => '?',
            'App\\Controller\\TaskController::detail' => '?',
            'App\\Controller\\TaskController::edit' => '?',
            'App\\Controller\\TaskController::index' => '?',
            'App\\Controller\\TaskController::myTasks' => '?',
            'App\\Controller\\UserController::login' => '?',
            'App\\Controller\\UserController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\TaskController:creation' => '?',
            'App\\Controller\\TaskController:delete' => '?',
            'App\\Controller\\TaskController:detail' => '?',
            'App\\Controller\\TaskController:edit' => '?',
            'App\\Controller\\TaskController:index' => '?',
            'App\\Controller\\TaskController:myTasks' => '?',
            'App\\Controller\\UserController:login' => '?',
            'App\\Controller\\UserController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
