<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSUA98xr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSUA98xr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSUA98xr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSUA98xr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSUA98xr\App_KernelDevDebugContainer([
    'container.build_hash' => 'SUA98xr',
    'container.build_id' => 'd75a9ed0',
    'container.build_time' => 1674524808,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSUA98xr');
