<?php

namespace ContainerSUA98xr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F1mZyAgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F1mZyAg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F1mZyAg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'animal' => ['privates', '.errored..service_locator.F1mZyAg.App\\Entity\\Animal', NULL, 'Cannot autowire service ".service_locator.F1mZyAg": it references class "App\\Entity\\Animal" but no such service exists.'],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'animal' => 'App\\Entity\\Animal',
            'doctrine' => '?',
        ]);
    }
}
