<?php

namespace ContainerSUA98xr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnimalService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.F1mZyAg.App\Entity\Animal' shared service.
     *
     * @return \App\Entity\Animal
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.F1mZyAg": it references class "App\\Entity\\Animal" but no such service exists.');
    }
}
