-- MySQL Script generated by MySQL Workbench
-- jue 27 oct 2022 10:42:07 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tienda_master` DEFAULT CHARACTER SET utf8 ;
USE `tienda_master` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_master`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Apellidos` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `rol` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_master`.`Categorias` (
  `idCategorias` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_master`.`Productos` (
  `idProductos` INT NOT NULL,
  `Categoria_id` INT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Precio` VARCHAR(45) NULL,
  `Stock` VARCHAR(45) NULL,
  `Oferta` VARCHAR(45) NULL,
  `Imagen` VARCHAR(45) NULL,
  PRIMARY KEY (`idProductos`),
  INDEX `fk_Productos_Categoria_idx` (`Categoria_id` ASC),
  CONSTRAINT `fk_Productos_Categoria`
    FOREIGN KEY (`Categoria_id`)
    REFERENCES `tienda_master`.`Categorias` (`idCategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_master`.`Pedidos` (
  `idPedidos` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NULL,
  `Localidad` VARCHAR(45) NULL,
  `Provincia` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Coste` VARCHAR(45) NULL,
  `Fecha` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idPedidos`),
  INDEX `fk_Pedidos_Usuarios_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_Pedidos_Usuarios`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `tienda_master`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lineas_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_master`.`lineas_pedidos` (
  `idlineas_pedidos` INT NOT NULL AUTO_INCREMENT,
  `pedido_id` INT NULL,
  `producto_id` INT NULL,
  `unidades` INT NULL,
  PRIMARY KEY (`idlineas_pedidos`),
  INDEX `fk_lineas_pedidos_Pedidos_idx` (`pedido_id` ASC) VISIBLE,
  INDEX `fk_lineas_pedidos_Producto_idx` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `fk_lineas_pedidos_Pedidos`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `tienda_master`.`Pedidos` (`idPedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lineas_pedidos_Producto`
    FOREIGN KEY (`producto_id`)
    REFERENCES `tienda_master`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
