<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJcyxi3i\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJcyxi3i/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJcyxi3i.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJcyxi3i\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJcyxi3i\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jcyxi3i',
    'container.build_id' => '6e4b3634',
    'container.build_time' => 1676513622,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJcyxi3i');
